### ISSUE TITLE
Axis gear opening en closing itself

### ISSUE THREAD

**Issue by JaPo78** [DPANET/AxisGear#2]
I have one flow in my Homey for opening the rollerblinds with Axis Gear. This flow dim’s it the Axis Gear to 100% (openening the rollerblinds).

When this flow is triggered it does open the rollerblind. But after about 4 - 5 minuten somehow the Axis Gear closes and opens the blind a few times. This happens every day. See pictures from the last 2 days.

The only flow connected with the Axis Gear is triggered by a fysical button. And it sets a notification on the Timeline. And the timeline shows the flow is only activated once each day, so i think its not the fysical button.

I already un-installed the gear from Homey and removed the App. This did not work.

![C4C3DD27-A0DA-42DF-B33C-72873EF571C8](https://user-images.githubusercontent.com/80591691/111036481-b2969e00-841f-11eb-8b83-b236238f1ac0.jpeg)

![EEC68F46-3614-493E-909A-BE7B4DCF8C62](https://user-images.githubusercontent.com/80591691/111036483-b3c7cb00-841f-11eb-9b10-31fd00024265.jpeg)

Thank you for helping!

Jaap
The Netherlands

**Comment by JaPo78** [comment]
This was not a Homey issue, the Axis Gear unit itself was the problem.

**Comment by Marc-AxisLabs** [comment]
@JaPo78 were you able to diagnose the problem with the AXIS Gear? Can you shed some light on it on the root cause?

**Comment by JaPo78** [comment]
I am not sure what the problem is. But when i operated the Axis manually (on the device) or with the Axis app or with Homey, and i opened 100% the Gear would close itself after 5-7 minutes.

When i open the Gear first for 75% and 1 minute later to 100% this doesn’t give any problems.

I think this problem happens because i cut off the Solar Panel and used the cable/connector to put it on an AC adapter (i can not buy the oem adapter from Axis) for better and constant power. The solar panel was not working great.



Met vriendelijke groet,


Jaap Nicolasen
Manager Portfolio & Solutions

Telefoon: (+31) 06 1015 7575
E-mail: ***@***.***
Website: www.centralpoint.nl


________________________________
Van: Marc-AxisLabs ***@***.***>
Verzonden: Thursday, March 25, 2021 6:43:04 PM
Aan: DPANET/AxisGear ***@***.***>
CC: JaPo78 ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [DPANET/AxisGear] Axis gear opening en closing itself (#2)


@JaPo78<https://github.com/JaPo78> were you able to diagnose the problem with the AXIS Gear? Can you shed some light on it on the root cause?

**Comment by Marc-AxisLabs** [comment]
Hi Jaap,

This is odd, I am not sure how the connector can cause such a bug even if you wired it up yourself. My first inclination is to think it is a firmware bug, but certainly not a common one.
Does this happen in both Smart Home mode (when the Zigbee chip is enabled and the device uses purple LED color for position) as well as BLE mode (when the device uses blue color for it's position)?
Also you likely tried this but just to confirm, this behavior persists after factory resetting (holding the top three buttons down for 5 sec initiates the reset process)?

Regards
Marc

**Comment by JaPo78** [comment]
Yes it happens in both modes and offcourse i did a factory reset, removed the app, removen and installed it from homey many times etc etc i tried a lot off things.

Can be a firmware problem, i am not sure.


Gr. Jaap

Op 25 mrt. 2021 om 19:55 heeft Marc-AxisLabs ***@***.***> het volgende geschreven:

﻿

Hi Jaap,

This is odd, I am not sure how the connector can cause such a bug even if you wired it up yourself. My first inclination is to think it is a firmware bug, but certainly not a common one.
Does this happen in both Smart Home mode (when the Zigbee chip is enabled and the device uses purple LED color for position) as well as BLE mode (when the device uses blue color for it's position)?
Also you likely tried this but just to confirm, this behavior persists after factory resetting (holding the top three buttons down for 5 sec initiates the reset process)?

Regards
Marc
